"""
context/data.py
───────────────
The Librarian's Book of Known Scams — 40 Patterns (extendable).
Categorized: 10 Govt, 10 Jobs, 10 Banking/UPI, 10 Shopping/Other.

Each entry has three language advice fields:
  advice_en  — English
  advice_hi  — Hindi (Devanagari)
  advice_hng — Hinglish (Roman script, village metaphor style)

To add more patterns, just append dicts to SCAM_DATA following the same schema.
"""

SCAM_DATA = [

    # ══════════════════════════════════════════════════════════════════
    # 🏛️  CATEGORY 1 — GOVERNMENT OFFERS & SCHEMES  (10 patterns)
    # ══════════════════════════════════════════════════════════════════
    {
        "id": "govt_001",
        "pattern": "PM-Kisan Installment Blocked",
        "content": "PM Kisan: Your 14th installment of ₹2000 is on hold. Verify bank details at http://pmkisan-verify.in to receive money.",
        "logic": "Targets farmers using official-sounding links. Real sites only end in .gov.in.",
        "category": "Govt. Scheme", "severity": "HIGH",
        "advice_en":  "Government portals never use .in or .com for schemes. Only visit .gov.in websites.",
        "advice_hi":  "सरकारी योजनाएं कभी .in या .com लिंक नहीं भेजतीं। सिर्फ .gov.in पर भरोसा करें।",
        "advice_hng": "Sarkaari kaam ke liye hamesha .gov.in check karein, ye nakli link hai!",
    },
    {
        "id": "govt_002",
        "pattern": "Free Laptop/Smartphone Yojna",
        "content": "Under PM Youth Scheme, students get a free laptop. Register with Aadhaar and pay ₹150 delivery fee at [link].",
        "logic": "Uses small 'delivery fee' as bait to steal Aadhaar data and card details.",
        "category": "Govt. Scheme", "severity": "MEDIUM",
        "advice_en":  "Free government schemes never ask for delivery or registration fees via links.",
        "advice_hi":  "मुफ्त सरकारी योजनाओं के लिए कभी भी लिंक पर पैसे या आधार कार्ड न दें।",
        "advice_hng": "Laptop ke laalach mein delivery fee mat bhariye, ye thagi ka tareeka hai!",
    },
    {
        "id": "govt_003",
        "pattern": "Digital Arrest / CBI Impersonation",
        "content": "CBI Alert: Your Aadhaar is linked to money laundering. You are under Digital Arrest. Join Skype call for verification.",
        "logic": "Police never arrest via video call or ask for money to 'clear' names.",
        "category": "Govt. Impersonation", "severity": "CRITICAL",
        "advice_en":  "No agency (CBI/ED/Police) performs 'Digital Arrest'. This is 100% fraud.",
        "advice_hi":  "पुलिस कभी भी वीडियो कॉल पर गिरफ्तार नहीं करती। यह एक बड़ा स्कैम है।",
        "advice_hng": "Digital Arrest jaisa kuch nahi hota — turant call kaatein aur 1930 pe report karein!",
    },
    {
        "id": "govt_004",
        "pattern": "Income Tax Refund Link",
        "content": "IT Dept: Your refund of ₹12,450 is approved. Click [link] to enter account details and receive money instantly.",
        "logic": "Phishing for bank login credentials under the guise of a refund.",
        "category": "Govt. Impersonation", "severity": "HIGH",
        "advice_en":  "Income Tax refunds are directly credited. They never ask for bank details via SMS links.",
        "advice_hi":  "आयकर विभाग रिफंड के लिए कभी भी SMS लिंक नहीं भेजता।",
        "advice_hng": "Refund ke naam pe bank account khali karne ki koshish hai, link mat kholiye!",
    },
    {
        "id": "govt_005",
        "pattern": "Ladli Behna / Women Subsidy",
        "content": "Registration for ₹1500 monthly subsidy is open. Pay ₹50 registration fee at [link] to start receiving benefits.",
        "logic": "Targets women with small fees to compromise UPI accounts.",
        "category": "Govt. Scheme", "severity": "MEDIUM",
        "advice_en":  "Official women welfare schemes are registered at Govt offices, not on random SMS links.",
        "advice_hi":  "सरकारी योजनाओं का रजिस्ट्रेशन सिर्फ सरकारी दफ्तरों या अधिकृत पोर्टल पर होता है।",
        "advice_hng": "Subsidy ke liye link pe paise mat dena — ye poora jhooth hai!",
    },
    {
        "id": "govt_006",
        "pattern": "Property Tax Penalty Threat",
        "content": "MC Alert: Your house tax is overdue. Pay ₹5000 fine today at http://tax-penalty.com to avoid property sealing.",
        "logic": "Fear of losing home forces victims to pay without checking authenticity.",
        "category": "Govt. Impersonation", "severity": "HIGH",
        "advice_en":  "Municipal corporations only accept tax on official portals or at the local office.",
        "advice_hi":  "नगर निगम कभी भी प्रॉपर्टी सील करने की धमकी SMS पर नहीं देता।",
        "advice_hng": "Ghar seal hone ki dhamki se darein nahi, sirf official office mein baat karein!",
    },
    {
        "id": "govt_007",
        "pattern": "Free Pilgrimage (Ayodhya/Hajj)",
        "content": "Register for Free VIP Darshan Pass. Pay ₹200 service charge and upload Aadhaar at [link].",
        "logic": "Uses religious sentiment to harvest sensitive identity data.",
        "category": "Govt. Scheme", "severity": "MEDIUM",
        "advice_en":  "Official pilgrimage boards do not request Aadhaar or fees via unverified links.",
        "advice_hi":  "दर्शन के नाम पर आधार कार्ड और पैसे मांगना धोखाधड़ी का संकेत है।",
        "advice_hng": "Bhagwan ke naam pe thagi ho rahi hai — Aadhaar aur paise mat dena!",
    },
    {
        "id": "govt_008",
        "pattern": "Ration Card Renewal",
        "content": "Your Ration Card will be deactivated tonight. Update Aadhaar and address at http://ration-update.top to continue.",
        "logic": "Targets low-income families by threatening their food security.",
        "category": "Govt. Impersonation", "severity": "HIGH",
        "advice_en":  "Ration card updates are done at local PDS offices or official state portals.",
        "advice_hi":  "राशन कार्ड बंद होने की धमकी देकर डेटा चोरी किया जा रहा है।",
        "advice_hng": "Ration band nahi hoga, ye link sirf aapka data lene ke liye hai!",
    },
    {
        "id": "govt_009",
        "pattern": "Electricity Bill 'Officer' Call",
        "content": "Your light will be cut at 9 PM. Call Officer Gupta at 9000000000. Pay ₹10 for update to avoid cut.",
        "logic": "The 'Small Update Fee' allows hackers to take control of your phone/UPI.",
        "category": "Utility Threat", "severity": "CRITICAL",
        "advice_en":  "Electricity boards never call with countdowns. Never pay 'update fees' to individuals.",
        "advice_hi":  "बिजली विभाग कभी भी फोन पर बिल अपडेट करने के लिए पैसे नहीं मांगता।",
        "advice_hng": "Bijli wale kabhi countdown nahi dete — ye 10 rupaye aapka account khali kar denge!",
    },
    {
        "id": "govt_010",
        "pattern": "EPFO / PF Withdrawal Help",
        "content": "Claim your PF amount of ₹50,000 instantly. Call our 'PF Agent' for fast processing. No fee required initially.",
        "logic": "Once the victim calls, the agent asks for UAN and OTP to steal the entire PF balance.",
        "category": "Govt. Impersonation", "severity": "CRITICAL",
        "advice_en":  "Only use the official EPFO portal (epfindia.gov.in) for PF claims. Never share OTP.",
        "advice_hi":  "PF निकालने के लिए किसी भी एजेंट को OTP या UAN न दें।",
        "advice_hng": "PF ke liye sirf sarkaari site use karein — Agent ke chakkar mein paise doob jayenge!",
    },

    # ══════════════════════════════════════════════════════════════════
    # 💼  CATEGORY 2 — JOB LETTERS & WORK FROM HOME  (10 patterns)
    # ══════════════════════════════════════════════════════════════════
    {
        "id": "job_001",
        "pattern": "YouTube Like/Task Job",
        "content": "Earn ₹5000 daily by liking YouTube videos. Part-time work for students. Contact HR on Telegram.",
        "logic": "The 'Prepaid Task' scam. They pay ₹150 first, then ask for 'investment' for bigger tasks.",
        "category": "Job Fraud", "severity": "HIGH",
        "advice_en":  "Legitimate companies do not pay thousands for liking videos. This is a Ponzi trap.",
        "advice_hi":  "वीडियो लाइक करने के इतने पैसे कोई नहीं देता। यह एक बड़ा इन्वेस्टमेंट फ्रॉड है।",
        "advice_hng": "Video like karke ameer nahi ban sakte — ye task scam se bachiye!",
    },
    {
        "id": "job_002",
        "pattern": "Airlines Ground Staff Hiring",
        "content": "Indigo/Air India hiring Ground Staff. Salary 45k. Pay ₹2500 for uniform and security deposit.",
        "logic": "Official airlines NEVER ask for money for uniforms or interviews.",
        "category": "Job Fraud", "severity": "MEDIUM",
        "advice_en":  "No reputed airline asks for money during the hiring process. Genuine jobs are free.",
        "advice_hi":  "कोई भी बड़ी एयरलाइन नौकरी के लिए पैसे नहीं मांगती।",
        "advice_hng": "Uniform ke naam pe paise maang rahe hain toh samajho naukri nakli hai!",
    },
    {
        "id": "job_003",
        "pattern": "Data Entry Software Fee",
        "content": "Typing job: Get ₹20 per page. Just buy our 'License Key' for ₹1500 to start the software.",
        "logic": "The software is fake. The goal is only to sell the 'License Key'.",
        "category": "Job Fraud", "severity": "MEDIUM",
        "advice_en":  "Never pay to get work. Genuine data entry jobs do not require license fees.",
        "advice_hi":  "काम शुरू करने के लिए पैसे मांगना धोखाधड़ी की निशानी है।",
        "advice_hng": "Kaam ke liye paise mat dena — licence key ke naam pe loot rahe hain!",
    },
    {
        "id": "job_004",
        "pattern": "Amazon Reviewer Scam",
        "content": "Become an Amazon Reviewer. Buy the product, review it, and get refund + 20% commission.",
        "logic": "Refunds only work for cheap items. When you buy expensive one, the scammer vanishes.",
        "category": "Job Fraud", "severity": "HIGH",
        "advice_en":  "Paying to review products is a common advance-fee scam.",
        "advice_hi":  "प्रोडक्ट रिव्यू के बदले रिफंड का वादा अक्सर झूठा होता है।",
        "advice_hng": "Shopping karke commission nahi milta — ye paise doobne ka rasta hai!",
    },
    {
        "id": "job_005",
        "pattern": "TCS/Infosys Fake Offer Letter",
        "content": "Congratulations! You are selected for TCS. Pay ₹5500 for Laptop Insurance to receive Offer Letter.",
        "logic": "Uses big company names to build trust, then asks for 'Insurance' or 'Laptop' fees.",
        "category": "Job Fraud", "severity": "HIGH",
        "advice_en":  "MNCs like TCS or Infosys never ask for money for laptops or insurance from candidates.",
        "advice_hi":  "बड़ी कम्पनियाँ नौकरी देने के लिए कभी पैसे नहीं मांगतीं।",
        "advice_hng": "TCS ke naam pe insurance fee mat bharna — ye nakli offer letter hai!",
    },
    {
        "id": "job_006",
        "pattern": "Hotel Staff / Cruise Job",
        "content": "Luxury Hotel in Dubai hiring Waiters/Staff. Free visa. Pay ₹8000 for medical clearance fee.",
        "logic": "The 'Medical Fee' is the scam. Once paid, the recruiter disappears.",
        "category": "Job Fraud", "severity": "MEDIUM",
        "advice_en":  "Dubai/Foreign job offers that ask for medical fees via UPI are always fraudulent.",
        "advice_hi":  "विदेश में नौकरी के लिए मेडिकल फीस के नाम पर पैसे देना खतरनाक है।",
        "advice_hng": "Foreign job ke liye medical fee mat dena — ye visa scam ho sakta hai!",
    },
    {
        "id": "job_007",
        "pattern": "Work from Home 'Captcha' Job",
        "content": "Solve Captchas and earn ₹30,000/month. Join with registration fee of ₹999.",
        "logic": "Low skill requirement + high pay + registration fee = Scam.",
        "category": "Job Fraud", "severity": "LOW",
        "advice_en":  "Captcha entry is not a high-paying job. Registration fees are the scammer's income.",
        "advice_hi":  "कैप्चा भरने के लिए रजिस्ट्रेशन फीस मांगना सरासर धोखाधड़ी है।",
        "advice_hng": "999 rupaye mat dena, Captcha bharne ke itne paise koi nahi deta!",
    },
    {
        "id": "job_008",
        "pattern": "Govt. Job Quota Setting",
        "content": "Get confirmed Railway/Bank job via 'Internal Quota'. Pay 1 Lakh advance. 100% Guaranteed.",
        "logic": "Exploits the desire for govt. jobs. There is no such 'Setting' or 'Internal Quota'.",
        "category": "Job Fraud", "severity": "HIGH",
        "advice_en":  "Government jobs are only through merit and official exams. Bribery offers are always scams.",
        "advice_hi":  "सरकारी नौकरी में 'सेटिंग' के नाम पर पैसे मांगना गैरकानूनी और फ्रॉड है।",
        "advice_hng": "Sarkaari naukri mein koi 'setting' nahi hoti, paise mat phansaana!",
    },
    {
        "id": "job_009",
        "pattern": "Part-Time Trading Assistant",
        "content": "Help our expert trade and earn 10% profit daily. No experience needed. Use our app [link].",
        "logic": "The app is a fake dashboard. To 'Withdraw', you must pay 'Taxes' first.",
        "category": "Job Fraud", "severity": "HIGH",
        "advice_en":  "Trading apps provided via SMS links are usually malware designed to steal capital.",
        "advice_hi":  "अनजान ऐप पर ट्रेडिंग करके पैसे कमाने का लालच सिर्फ एक जाल है।",
        "advice_hng": "Trading assistant ke naam pe aapka account khali ho jayega — link mat kholna!",
    },
    {
        "id": "job_010",
        "pattern": "SMS Sending Job",
        "content": "Send 100 SMS daily from your phone and earn ₹500. Pay ₹500 for server access.",
        "logic": "Your number will be blocked for spamming, and you lose the access fee.",
        "category": "Job Fraud", "severity": "LOW",
        "advice_en":  "Sending bulk SMS from a personal SIM is illegal and a common scam setup.",
        "advice_hi":  "पर्सनल नंबर से SMS भेजने का काम करना आपके लिए कानूनी मुसीबत बन सकता है।",
        "advice_hng": "SMS bhej kar paise nahi milte, balki aapka number block ho jayega!",
    },

    # ══════════════════════════════════════════════════════════════════
    # 💳  CATEGORY 3 — BANKING & UPI  (10 patterns)
    # ══════════════════════════════════════════════════════════════════
    {
        "id": "bank_001",
        "pattern": "G-Pay/PhonePe Cashback PIN",
        "content": "Congrats! You won ₹999 cashback. Click 'Pay/Claim' and enter UPI PIN to receive money.",
        "logic": "PIN is ONLY for sending money, NEVER for receiving.",
        "category": "UPI Fraud", "severity": "CRITICAL",
        "advice_en":  "You NEVER need to enter a PIN to receive money. If asked for a PIN, it's a theft attempt.",
        "advice_hi":  "पैसे पाने के लिए कभी भी PIN डालने की ज़रूरत नहीं होती।",
        "advice_hng": "PIN daalne ka matlab hai paise BHEJNA — paisa lene ke liye PIN nahi chahiye!",
    },
    {
        "id": "bank_002",
        "pattern": "KYC Expired Link",
        "content": "Dear Customer, your SBI account KYC is expired. Your account will be frozen. Update now: http://sbi-kyc-verify.net",
        "logic": "Panic bait with a fake domain (.net instead of .sbi or .co.in).",
        "category": "Banking Fraud", "severity": "CRITICAL",
        "advice_en":  "Banks never ask for KYC updates via SMS links. Always visit the branch or official app.",
        "advice_hi":  "बैंक कभी भी SMS लिंक के ज़रिए KYC अपडेट नहीं मांगते।",
        "advice_hng": "Bank link bhej kar KYC nahi maangta — ye aapka password chori karne ka tareeka hai!",
    },
    {
        "id": "bank_003",
        "pattern": "Wrong Transfer Refund",
        "content": "Galti se ₹5000 aapko bhej diye. Hospital emergency hai. Please wapas kar do [UPI ID].",
        "logic": "The scammer sends a fake 'Money Received' SMS and asks for real money back.",
        "category": "UPI Fraud", "severity": "HIGH",
        "advice_en":  "Check your bank balance directly first. Do not trust SMS notifications alone.",
        "advice_hi":  "बिना बैंक बैलेंस चेक किए कभी भी किसी को पैसे वापस न भेजें।",
        "advice_hng": "Pehle bank account check karein — bina dekhe paise wapas mat bhejna!",
    },
    {
        "id": "bank_004",
        "pattern": "Credit Card Limit Increase",
        "content": "Increase your HDFC CC limit to 10 Lakhs. No docs. Valid for 2 hours: [fake-link]",
        "logic": "Steals Card number, CVV, and OTP via phishing page.",
        "category": "Banking Fraud", "severity": "HIGH",
        "advice_en":  "Limit increases are only managed via official banking apps or customer care.",
        "advice_hi":  "क्रेडिट कार्ड की लिमिट बढ़ाने के लिए लिंक पर कार्ड डिटेल्स न डालें।",
        "advice_hng": "Card limit ke naam pe link bhejna 100% fraud hai — details mat dena!",
    },
    {
        "id": "bank_005",
        "pattern": "OLX Buyer QR Code",
        "content": "I am buying your OLX item. Scan this QR code to receive the advance payment.",
        "logic": "Scanning a QR and entering a PIN will DEDUCT money from your account.",
        "category": "UPI Fraud", "severity": "CRITICAL",
        "advice_en":  "Scanning a QR code is for PAYING, not for receiving money.",
        "advice_hi":  "QR कोड स्कैन करने का मतलब है कि आप पैसे दे रहे हैं, ले नहीं रहे।",
        "advice_hng": "QR code scan karne se paise kat-te hain, aate nahi — savdhan rahein!",
    },
    {
        "id": "bank_006",
        "pattern": "Sim Swap / 5G Upgrade",
        "content": "Your SIM will be blocked. Call to upgrade to 5G. Share your 20-digit SIM number for activation.",
        "logic": "Scammer clones your SIM to hijack OTPs for banking.",
        "category": "Telecom Fraud", "severity": "CRITICAL",
        "advice_en":  "Never share your SIM serial number or OTP with anyone claiming to be from Jio/Airtel.",
        "advice_hi":  "सिम अपग्रेड के नाम पर कभी भी अपनी सिम डिटेल्स या OTP न दें।",
        "advice_hng": "SIM upgrade ke liye koi call nahi aata — ye aapka OTP lene ka jaal hai!",
    },
    {
        "id": "bank_007",
        "pattern": "Reward Points Expiry",
        "content": "Your 5000 Reward points (₹5000) expire today. Convert to cash now: [link]",
        "logic": "The link leads to a fake bank login page.",
        "category": "Banking Fraud", "severity": "HIGH",
        "advice_en":  "Reward points are redeemed inside the bank's official portal, never via external links.",
        "advice_hi":  "रिवॉर्ड पॉइंट्स को कैश में बदलने के लिए लिंक पर बैंक पासवर्ड न डालें।",
        "advice_hng": "Points ke chakkar mein password mat dena — ye fake link hai!",
    },
    {
        "id": "bank_008",
        "pattern": "PAN Card Update Threat",
        "content": "Your PAN card is not linked to Aadhaar. Your account will be blocked. Update at [link].",
        "logic": "Uses recent government mandates to create urgency and steal PAN/Bank info.",
        "category": "Govt. Impersonation", "severity": "HIGH",
        "advice_en":  "Use only incometax.gov.in to link PAN and Aadhaar. Ignore all other links.",
        "advice_hi":  "PAN-Aadhaar लिंक करने के लिए सिर्फ सरकारी वेबसाइट का उपयोग करें।",
        "advice_hng": "Sarkaari link hamesha .gov.in hota hai — ye link fraud hai!",
    },
    {
        "id": "bank_009",
        "pattern": "Predatory Loan App",
        "content": "Loan approved! ₹50,000 instantly without docs. Download 'QuickCash' app now: [link]",
        "logic": "The app steals your contacts and gallery to blackmail you with edited photos later.",
        "category": "Financial Fraud", "severity": "CRITICAL",
        "advice_en":  "Never install loan apps from links. They are used for extortion and data theft.",
        "advice_hi":  "अनजान लोन ऐप्स आपकी निजी जानकारी और फोटो चोरी कर सकती हैं।",
        "advice_hng": "Anjaan loan app install mat karna — ye blackmailing ka dhanda hai!",
    },
    {
        "id": "bank_010",
        "pattern": "WhatsApp Pink / Update",
        "content": "New Pink WhatsApp with more features. Download official update here: [link]",
        "logic": "This is malware. It steals your banking OTPs by reading your incoming SMS.",
        "category": "Malware", "severity": "CRITICAL",
        "advice_en":  "WhatsApp updates only happen through the Play Store/App Store. Links are malware.",
        "advice_hi":  "पिंक व्हाट्सएप एक वायरस है जो आपका डेटा और पैसे चोरी कर सकता है।",
        "advice_hng": "Pink WhatsApp mat download karna — ye virus hai jo OTP chori karta hai!",
    },

    # ══════════════════════════════════════════════════════════════════
    # 🎁  CATEGORY 4 — SHOPPING, SOCIAL & LOTTERY  (10 patterns)
    # ══════════════════════════════════════════════════════════════════
    {
        "id": "misc_001",
        "pattern": "iPhone for ₹999 Scam",
        "content": "Unclaimed Amazon Warehouse Sale! iPhone 15 only ₹999. Only 5 units left. Order now: [link]",
        "logic": "Classic 'Too good to be true'. Steals credit card info and shipping fees.",
        "category": "Shopping Fraud", "severity": "HIGH",
        "advice_en":  "No brand-new iPhone is ever sold for ₹999. These sites steal your card details.",
        "advice_hi":  "₹999 में iPhone मिलना असंभव है। ये साइटें आपकी कार्ड डिटेल्स चुरा लेती हैं।",
        "advice_hng": "999 mein iPhone nahi milta — ye link aapka ATM card khali kar dega!",
    },
    {
        "id": "misc_002",
        "pattern": "KBC / Lottery Win SMS",
        "content": "You have won ₹25 Lakh in KBC Lucky Draw. Call Mr. Sharma at 9800000000 to claim prize.",
        "logic": "Asks for 'Tax' or 'Processing Fee' before releasing the prize. Prize never comes.",
        "category": "Lottery Fraud", "severity": "HIGH",
        "advice_en":  "KBC and all legitimate lotteries never ask for fees to release winnings.",
        "advice_hi":  "KBC कभी भी फोन पर इनाम नहीं देती। इनाम से पहले पैसे मांगना धोखाधड़ी है।",
        "advice_hng": "KBC wale pehle paise nahi maangte — ye lottery scam hai, call mat karna!",
    },
    {
        "id": "misc_003",
        "pattern": "Matrimony Profile Fraud",
        "content": "Hi, I am settled abroad. Sending you a gift. Pay ₹500 customs clearance to receive it.",
        "logic": "Romance scam. Gift never arrives. Multiple customs/fee requests follow.",
        "category": "Social Engineering", "severity": "HIGH",
        "advice_en":  "Strangers sending expensive gifts from abroad and asking for customs fees are always scammers.",
        "advice_hi":  "विदेश से गिफ्ट के नाम पर कस्टम फीस मांगना एक प्रसिद्ध धोखाधड़ी है।",
        "advice_hng": "Anjaane ne gift bheja aur customs fee maangi — ye romance fraud hai!",
    },
    {
        "id": "misc_004",
        "pattern": "Fake Customer Care Number",
        "content": "Amazon/Flipkart Customer Care: 9811111111. Call for refund on your damaged order.",
        "logic": "Scammer poses as support, asks for OTP/UPI PIN to 'process the refund'.",
        "category": "Impersonation", "severity": "HIGH",
        "advice_en":  "Always find customer care numbers from the official app/website only.",
        "advice_hi":  "कस्टमर केयर का नंबर हमेशा ऑफिशियल ऐप से ढूंढें, Google से नहीं।",
        "advice_hng": "Google pe customer care number mat dhundho — ye nakli number ho sakta hai!",
    },
    {
        "id": "misc_005",
        "pattern": "Cheap Tour Package",
        "content": "Manali/Goa tour package 3 nights only ₹1999. Book now. Pay advance ₹500 on WhatsApp.",
        "logic": "Once advance is paid, the agent goes silent or demands more money.",
        "category": "Shopping Fraud", "severity": "MEDIUM",
        "advice_en":  "Book tours only through verified platforms. Advance payments on WhatsApp are risky.",
        "advice_hi":  "WhatsApp पर टूर के लिए एडवांस पेमेंट देना बहुत जोखिम भरा है।",
        "advice_hng": "WhatsApp pe tour booking mat karna — paise le ke bhaag jaate hain!",
    },
    {
        "id": "misc_006",
        "pattern": "Charity / Flood Relief Fake",
        "content": "Donate for flood victims in Assam. UPI: relief@ybl. Every rupee counts!",
        "logic": "Exploits generosity during natural disasters. UPI goes to a personal account.",
        "category": "Social Engineering", "severity": "MEDIUM",
        "advice_en":  "Donate only through verified NGOs or PM Relief Fund (pmcares.gov.in).",
        "advice_hi":  "आपदा राहत के नाम पर दान करते समय सिर्फ सरकारी या जाने-माने NGO को दें।",
        "advice_hng": "Donation ke naam pe bhi thagi hoti hai — sirf sarkari fund mein daan karein!",
    },
    {
        "id": "misc_007",
        "pattern": "Sextortion / Nude Video Call",
        "content": "I have your video from earlier call. Pay ₹5000 or I will send it to your contacts.",
        "logic": "Screen-recorded random call. Victim is blackmailed with manipulated footage.",
        "category": "Cyber Crime", "severity": "CRITICAL",
        "advice_en":  "Do not pay. Report immediately to cybercrime.gov.in or call 1930.",
        "advice_hi":  "पैसे मत दीजिए। तुरंत cybercrime.gov.in पर शिकायत करें।",
        "advice_hng": "Paise mat dena — seedha 1930 pe call karo aur report karo!",
    },
    {
        "id": "misc_008",
        "pattern": "Second-Hand Car Advance",
        "content": "Selling my car (Army transfer). Price ₹1.5L. Pay ₹10,000 token advance and I will ship it.",
        "logic": "Car never exists. Token advance is stolen. Common on OLX/Facebook groups.",
        "category": "Shopping Fraud", "severity": "HIGH",
        "advice_en":  "Never pay advance for second-hand goods without physically seeing the item.",
        "advice_hi":  "गाड़ी देखे बिना एडवांस देना खतरनाक है। हमेशा खुद जाकर गाड़ी देखें।",
        "advice_hng": "Gaadi dekhe bina advance mat dena — army transfer wala scam bahut common hai!",
    },
    {
        "id": "misc_009",
        "pattern": "Fake Internship / Certificate",
        "content": "Get internship certificate from IIT/IIM. Pay ₹799 for premium certificate. Boost your resume!",
        "logic": "Certificate is worthless and PDF-generated. No actual internship takes place.",
        "category": "Job Fraud", "severity": "LOW",
        "advice_en":  "IIT/IIM certifications are only issued through their official portals, not via WhatsApp.",
        "advice_hi":  "IIT/IIM सर्टिफिकेट के नाम पर WhatsApp पर पैसे मांगना फ्रॉड है।",
        "advice_hng": "799 rupaye mein IIT certificate nahi milta — ye kagaz ka tukda hoga!",
    },
    {
        "id": "misc_010",
        "pattern": "Astrology / Vashikaran Fraud",
        "content": "Remove black magic from your family. Pay ₹2100 for pooja samagri. 100% guaranteed solution.",
        "logic": "Exploits fear and superstition. Repeated payments are demanded for 'stronger rituals'.",
        "category": "Social Engineering", "severity": "MEDIUM",
        "advice_en":  "No genuine pandit or astrologer demands UPI payments for 'removing curses'.",
        "advice_hi":  "ऑनलाइन वशीकरण या काले जादू को हटाने के नाम पर पैसे मांगना धोखाधड़ी है।",
        "advice_hng": "Vashikaran ke naam pe paise maangne wale thag hain — bilkul mat dena!",
    },
]
